### ISSUE TITLE
When upgrade to 2.0, `/paper-styles/element-styles/paper-material-styles.html` Not Found

### ISSUE THREAD

**Issue by andrewspy** [PolymerElements/paper-card#101]
### Description
When upgrading to paper-card 2.0, `/paper-styles/element-styles/paper-material-styles.html` Not Found.

### Expected outcome

No error

### Actual outcome

```
GET http://localhost:8081/bower_components/paper-styles/element-styles/paper-material-styles.html 404 (Not Found)
polymer.html:2654 Could not find style data in module named paper-material-styles
```

### Live Demo
N/A

### Steps to reproduce

Upgrade from 

```
"paper-card": "PolymerElements/paper-card#^1.1.0",
```

to

```
"paper-card": "PolymerElements/paper-card#^2.0.0",
```

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
It's definitely there: https://github.com/PolymerElements/paper-styles/blob/master/element-styles/paper-material-styles.html#L34
I think your bower dependencies are not updated, so I recommend removing your `bower_components` folder and re-installing
