### ISSUE TITLE
Vertical images are being turned

### ISSUE THREAD

**Issue by profhase** [PolymerElements/paper-card#103]
### Description
When having a vertical iimage (width < height) the image in the paper card is being turned.

### Expected outcome
Image scales normally

### Actual outcome

image is turned so that it is on the side

### Steps to reproduce

Insert this pic
### Browsers Affected

- [ x] Chrome
- [x ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by profhase** [comment]
Sorry, my fault. The image had exif tags set. Also the browser seems to interpret it (if opened alone)

**Comment by notwaldorf** [comment]
Whew, glad it got sorted
