### ISSUE TITLE
Not on polygit

### ISSUE THREAD

**Issue by maxiplay** [PolymerElements/paper-card#109]
http://polygit.org/components/paper-button/paper-button.html => OK

http://polygit.org/components/paper-card/paper-card.html => KO

**Comment by web-padawan** [comment]
It looks like `paper-card` should be published to `bower`. 
I faced this issue today while trying [private-bower](http://hacklone.github.io/private-bower/)

There is an outdated [unofficial package](https://github.com/andytuwm/paper-card) BTW, this might be the reason.

@notwaldorf @robdodson could you please publish `paper-card` to bower?

**Comment by robdodson** [comment]
I don't think the Polymer team publishes any components to the bower registery. We always use the built-in feature of bower to clone from github. So `bower install PolymerElements/paper-card`.
