### ISSUE TITLE
Question: <style> inside <template>

### ISSUE THREAD

**Issue by clintwood** [PolymerElements/paper-card#12]
I noticed that `paper-card` has it's `<style>` tag inside the outermost `<template>` tag and I'm trying to understand the significance of doing this specifically when the very first paragraph on styling explicitly says don't do this.  What effect does this have in the case of `paper-card`?

**Comment by notwaldorf** [comment]
The `<style>` inside the `<template>` is a new recommendation, as of Polymer 1.1.0 (see: https://blog.polymer-project.org/announcements/2015/08/13/1.1-release/). Most other elements have not been updated yet; `paper-card` was one of the early ones :)

**Comment by samccone** [comment]
yep @clintwood there is a tiny perf boost as well :clap:

**Comment by clintwood** [comment]
@notwaldorf, Thanks, missed that!  @samccone, like it!
