### ISSUE TITLE
Rounder corners

### ISSUE THREAD

**Issue by antonmoiseev** [PolymerElements/paper-card#13]
According to the spec cards should have rounded corners. Border radius is set for the host:
```html
:host {
    border-radius: 2px;
}
```
However `paper-material#shadow` element prevents them from actually being rounded.
<hr>
### Before
![image](https://cloud.githubusercontent.com/assets/182853/9491813/86bb1e0e-4bfa-11e5-86a0-3a688a7b1994.png)
<hr>
### After
![image](https://cloud.githubusercontent.com/assets/182853/9491823/a058f728-4bfa-11e5-817e-41bec144e2d8.png)

**Comment by samccone** [comment]
![Uploading Screen Shot 2015-08-26 at 6.32.17 AM.png…]()

lgtm

**Comment by antonmoiseev** [comment]
It's just an issue report but if lgtm can be considered as a blessing for a PR, I'll do it in a minute :smile:

**Comment by samccone** [comment]
@antonmoiseev I would wait for one of the maintainers to comment here, there might be a reason for this :)

**Comment by antonmoiseev** [comment]
Got you, I thought you are one of the maintainers. But the problem is not only they are not rounded by default, if you locally set:
```css
paper-card {
  border-radius: 20px; /* 20px just for illustration */
}
```
You'll get this:
![image](https://cloud.githubusercontent.com/assets/182853/9493919/906512b4-4c0b-11e5-84d2-c22d5f8a4ae1.png)

**Comment by addyosmani** [comment]
As far as I can tell, fixing `paper-material#shadow` from preventing corner roundness would be the right way to match the behaviour in-spec here. Let's wait for some input from @notwaldorf :icecream:

**Comment by notwaldorf** [comment]
Yeah, fixing `#shadow` totally makes sense, and I would be delighted if you sent a PR for it 😊

**Comment by samccone** [comment]
I think we are all set on master with this now.

@notwaldorf should we cut a new release of this?

**Comment by notwaldorf** [comment]
Already done!
