### ISSUE TITLE
swipe functionality?

### ISSUE THREAD

**Issue by s-devaney** [PolymerElements/paper-card#14]
Is swipe functionality being considered for this element? Much like Google Now where you can swipe the card to dismiss

**Comment by notwaldorf** [comment]
Ah, yes. Sorry, this completely fell off my radar. 
I think we want an `<iron-swipeable-container>` or something that would allow you to swipe any of its children. I'll start looking into it.

**Comment by samccone** [comment]
based on a quick look at the spec it looks like what you are asking for is a card collection.

<img width="362" alt="screen shot 2015-08-26 at 10 29 49 am" src="https://cloud.githubusercontent.com/assets/883126/9501330/f2367808-4be7-11e5-8657-8fa99a96ca81.png">

It might be really cool to have a **card collection** paper element :page_facing_up: 


thoughts? :seedling:

**Comment by notwaldorf** [comment]
@samccone yeah `<iron-swipeable-collection>` would be that. There's no reason (I don't think) that only cards should be swipeable... They would just need to use a behaviour based on the 0.5 [swipeable-card](https://github.com/PolymerLabs/swipeable-card/blob/master/swipeable-card.html). I think. Famous last words.

**Comment by samccone** [comment]
👍👍👍 sgtm 🌠

**Comment by ranjeet-choudhary** [comment]
+1

**Comment by abdonrd** [comment]
Something like `iron-swipeable` sounds good!

**Comment by notwaldorf** [comment]
Update: `iron-swipeable-container` is a thing! The PR is still in review, but should be ready soon: https://github.com/PolymerElements/iron-swipeable-container/pull/2

**Comment by notwaldorf** [comment]
'iron-swipeable-container' has landed! Long live `iron-swipeable-container`!

**Comment by kbwatts** [comment]
<3
