### ISSUE TITLE
Styling is not being applied 

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-card#16]
###### Polymer 1.1

`--paper-card-header-color:` is not being applied to the header in:

```css
    .header {
      color: var(--paper-pink-500);
      --paper-card-header-color: var(--paper-pink-500);
    }
``` 

```html 
<paper-card heading="Cloud Image Share" class="header" image="../img/cloud-share-image.jpg">
```

However, to prove that I do have the `paper-styles` colors working, the `color: var(--paper-pink-500)` does work successfully. 

I am using the `.pink` example in [index.html demo](https://github.com/PolymerElements/paper-card/blob/master/demo/index.html) to go by.

###### Update: 
it seems none of the styling is being applied other than the shadow. For instance, `class="card-actions"` is not being applied ether:

![pic2](https://cloud.githubusercontent.com/assets/887815/9564841/c08dd842-4ea2-11e5-94ce-1f798c00969d.jpg)

Here is more of the code:

```html
<dom-module id="portfolio-page">
  <style>
    :host[show] {
      @apply(--layout-horizontal);
      @apply(--layout-center-justified);
      height: 50%;
     }

    paper-card {
      max-width: 400px;
      margin-bottom: 16px;
    }

    section {
      width: 100%;
      background-color: var(--paper-grey-50);
    }

    .header {
      --paper-card-header-color: var(--paper-pink-500);
    }

    @media all and (min-width: 1200px) {
      section {
        width: 90%;
      }
    }
  </style>

  <template>
      <section>
        <div nclick="page('/')"
          class="vertical layout">
          <paper-card heading="Cloud Image Share" class="header" image="../img/cloud-share-image.jpg">
            <div class="card-content">
              blah blah blah
            </div>
            <div class="card-actions">
              <paper-button>No</paper-button>
              <paper-button>Yes</paper-button>
            </div>
          </paper-card>`
        </div>
      </section>
  </template>

  <script>
    Polymer({
      is: "portfolio-page",
      properties: {
      ///NOTE: old code...I used to have it in a dom-if but I stripped the conditional out to trouble shoot
                    this  
      show: {
          type: Boolean,
          reflectToAttribute: true,
          value: true
        }
      },
      toggleShow: function() {
        this.show = !this.show;
      }
    });
  </script>
</dom-module>

```

**Comment by dman777** [comment]
Good news! I reinstalled with bower and I chose `3) polymer#^1.1.0`. I didn't see this before in my terminal and I chose ` 2) polymer#^1.0.0 ` which I think tech. should be correct since the  carrot symbolized 1.0.0 or greater....but obviously not the right choice. 

I will close this bug.

**Comment by notwaldorf** [comment]
Sweet, glad it worked! Also, thanks for the nice words -- we appreciate them! 🎉
