### ISSUE TITLE
Consider optimizing performance

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-card#20]
Since users often create many instances of this element, it will especially benefit from performance optimizations. Consider lazily creating optional or user initiated functionality (e.g. paper-material), leveraging behaviors over composition (e.g. paper-material), streamlining styling, and eliminating or simplifying features (e.g. behaviors).

**Comment by samccone** [comment]
@ebidel What perf metrics should we be measuring here / optimizing for?

**Comment by ebidel** [comment]
Less instances is good. If the paper-material feature is never used, its DOM shouldn't be created. You can also `display: none` elements that are non-visual custom elements to take them out of the render tree. Like https://github.com/PolymerElements/iron-ajax/blob/master/iron-ajax.html#L64

**Comment by notwaldorf** [comment]
Just to chime in: unfortunately, I think it's pretty unlikely that `paper-material` won't be used (unlike, say `paper-button`), since the whole point of a `paper-card` is to look like the MD lifted paper + contents :)

**Comment by ranjeet-choudhary** [comment]
+1
