### ISSUE TITLE
[ERROR] :host ::content in 'card-action' and 'card-content'

### ISSUE THREAD

**Issue by SayChunKim** [PolymerElements/paper-card#23]
I have bower installed paper-card library but i have met the padding issue and classes are not included as tried according to docs of element-polymer-project.org. 

Error Screenshot as below:

![error](https://cloud.githubusercontent.com/assets/7574227/9979990/7ba4e062-5fba-11e5-856a-7f9be279e603.JPG)

I managed to make workaround fix by removing <code>:host ::content</code> in both classes in paper-card.html

Tested with another colleague's site yet met same problem. Did someone manage replicate the issue?

Thanks

**Comment by ranjeet-choudhary** [comment]
try putting content with "card-content" class

**Comment by SayChunKim** [comment]
I followed the code according the docs, yes i did include the content with card-content class, but the paper-card.html doesn't recognize the class for calling, so i would like to request removal of <code>:host ::content </code> if the changes are acceptable

**Comment by notwaldorf** [comment]
Can you reproduce this in a jsbin, or post a snippet of your code? The `:host ::content` is needed to make the card work in the shadow DOM, so it cannot be removed. Something like this should work (note that the `card-content` class is not optional:
```html
<paper-card heading="Card Title">
  <div class="card-content">Some content</div>
  <div class="card-actions">
    <paper-button>Some action</paper-button>
  </div>
</paper-card>
```

**Comment by SayChunKim** [comment]
hi @notwaldorf the code snippet i have tried, is exactly same within the docs in elements.polymer which is same snippet as you have suggested. Yes, my previous card was included the classes required but the style of <code>card-content</code> and <code>card-actions</code> not working in the browsers tested: Mozilla Firefox 40.0.3 and Chrome 45.0.2454.93 m

This is the screenshot provided. Hope helps

![error](https://cloud.githubusercontent.com/assets/7574227/10005812/005b83a6-60ec-11e5-89d2-298efb45f805.JPG)

**Comment by notwaldorf** [comment]
Can you please post your code, or a jsbin? I can't reproduce your issue otherwise :(

**Comment by SayChunKim** [comment]
I'm not sure jsbin helps much since i started fresh from polymer starter kit, but i did similarly as below, i just added the code within <code>body</code>:

https://jsbin.com/jezipikubi/edit?html,css,output

Hope helps @notwaldorf

**Comment by notwaldorf** [comment]
You are not importing `paper-card`, nor `webcomponents-lite.js`. Once you do, this looks fine: https://jsbin.com/pexuhayuhu/1/edit?html,css,output

<img width="202" alt="screen shot 2015-09-21 at 3 20 37 pm" src="https://cloud.githubusercontent.com/assets/1369170/10006701/53aeb47e-6074-11e5-8c9d-be085844dc3b.png">

**Comment by SayChunKim** [comment]
Hmm, i will try see check from polygit and try again. I will close this until if problem persists. Thanks @notwaldorf  :)
