### ISSUE TITLE
Feature request- expand arrow in paper-card

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-card#39]
According to Google Design, paper-cards should not contain to much information. In their examples, they show an expand arrow for more information. 

This would be a nice feature to have in `paper-card`. Also, there is no paper expand arrow like the one they use available. I checked `iron icons` and did not see one similar. 

![arrow](https://cloud.githubusercontent.com/assets/887815/11022624/3eda177a-865b-11e5-9375-7967ff1f260d.png)

**Comment by addyosmani** [comment]
Is the expand arrow not the same as this one? https://www.google.com/design/icons/#ic_keyboard_arrow_up

**Comment by notwaldorf** [comment]
Yup, @addyosmani is right, I think that's just `hardware:keyboard-arrow-up`: https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html`. You can implement this expander thing with an `iron-collapse`, but I think you're right that an example will be nice. On it!

**Comment by dman777** [comment]
@notwaldorf thanks for the example, that was a excellent example that I used in my own code! Awesome code there with `iconButton.icon = ironElement.opened ? 'hardware:keyboard-arrow-up...`

 This is minor, I just wanted to mention that on the Google Design site for the cards the arrow for unexpanded content is pointing upwards and in the demo it is pointing downwards.

**Comment by notwaldorf** [comment]
@dman777 Oh, ha! I would totally merge a PR fixing this, if you were to send one :)

**Comment by dman777** [comment]
:+1: Sure! I'll get on it :)
