### ISSUE TITLE
Problem with mixins in production builds

### ISSUE THREAD

**Issue by rycastaneda** [PolymerElements/paper-card#44]
Not sure if this is the right place to post this. There is a problem when minifying polymer mixins like in polymer starter kit that those with 
```
    width: 100%;
   --iron-image-width: 100%;
```
will result to a mess like this
```
    width: 100% --iron-image-width: 100%;
```
example can be found on https://github.com/PolymerElements/paper-card/blob/master/paper-card.html#L87

**Comment by ebidel** [comment]
How are you minimizing?

**Comment by notwaldorf** [comment]
This doesn't look like a `paper-card` issue, it looks like a generic issue with whatever minifier you are using, and it not understanding custom properties correctly. If this is an issue from PSK, then I recommend maybe opening an issue there.

/cc @addyosmani
