### ISSUE TITLE
paper-card-action area is not sticking to the bottom of paper-card

### ISSUE THREAD

**Issue by emfluenceindia** [PolymerElements/paper-card#48]
HTML
```
 <paper-card class="media-responsive" heading="Nearest customers">
     <div class="card-content">
          <nearest-customers id="nearestCustomers" card-view-max-records="3"></nearest-customers>
     </div>
     <div class="card-actions card-footer">
          <div style="float:right;text-align:right">
               <a data-route="allcustomers" href="/full-customer-list">Full customer list&nbsp;
                     <iron-icon class="iron-icon-12" icon="fa:arrow-right"></iron-icon></a>
          </div>
          <div class="clear"></div>
     </div>
</paper-card>
```

CSS
```
paper-card {
     position: relative !important;
     width: 100%;
     margin-bottom: 10px;
     height: auto !important;
}
.card-actions {
     position: relative !important;
     bottom: 0 !important;
}
```

Custom Style:

```
<style is="custom-style">
     paper-card {
            --paper-card-header-color: #000000;
            --paper-card-header-text:{
                font-size:15px;
                margin:0 auto;
            };
            --paper-card-header: {
                /*@apply(--layout-horizontal);
                @apply(--layout-center);*/
                margin:0 auto;
                border-bottom:1px solid #dddddd !important;
                padding:0;
                margin-bottom:0px !important;
            };
            
            --paper-card-actions {
                border-top: 1px solid #e8e8e8;
                padding: 5px 16px;
                position:relative !important;
                @apply(--paper-card-actions);
            }
        }
</style>
```

Output (please see attached image)
![stickey-card-action-issue](https://cloud.githubusercontent.com/assets/11072678/11590831/1191586a-9ab9-11e5-8fe7-cf79f7a98879.jpg)

How can I achieve this?

**Comment by notwaldorf** [comment]
Why are you using a `paper-card`? It seems like you just want a vertical layout, that's maybe inside a `paper-material` for the box shadow. `paper-card` has a very specific look it's trying to achieve (https://www.google.com/design/spec/components/cards.html), and it doesn't seem like you're going for that.

**Comment by notwaldorf** [comment]
Also, when I run your example, it looks like the "full customer list" bit is sticking to the bottom http://jsbin.com/quseje/edit?html,output, so maybe there's some margins you're applying somewhere?

**Comment by emfluenceindia** [comment]
I am not setting any margin anywhere. What happening is the height of a `paper-card` is being adjusted according to the `paper-card` with maximum height in that row. I will try `paper-material` and see how it goes. Will come back with what I get.

**Comment by notwaldorf** [comment]
Thanks. Going to close this issue in the meantime. Please re-open this if you have more repo steps (a jsbin that works would be great!)

**Comment by jfletcher-nuxeo** [comment]
So @notwaldorf I'm not OP but this is still (or again) happening. I was unable to get a working example in jsfiddle or jsbin, sorry. I've got a working example using Polymer CLI but not sure how to post that. I'll attach a zip at least...

[paper-card-bug.zip](https://github.com/PolymerElements/paper-card/files/2375934/paper-card-bug.zip)
