### ISSUE TITLE
Optimize Demo png files

### ISSUE THREAD

**Issue by chuckh** [PolymerElements/paper-card#59]
@notwaldorf / @addyosmani look at optimizing `donuts.png` and `home.png`.   Paper-card went from 28.4 KB to 11.5 MB to download.

**Comment by robdodson** [comment]
omg yes +1!

**Comment by addyosmani** [comment]
CL incoming to fix this. Thanks for catching the perf optimisation here :speedboat:

**Comment by notwaldorf** [comment]
Eeeeek I'm sorry errrone! Thanks @addyosmani!

**Comment by jfletcher-nuxeo** [comment]
This isn't actually fixed, the file sizes before and after 0d209f72c96c646cc88ea3c12fb7bd7440f5aacb are the same.  For example `house.png` is still 5.7MB.  Given the resolution it's being used at in the demo (384x216), it should be more like 170K depending on what you use to resize (I used Photoshop with "Automatic" resampling).
