### ISSUE TITLE
How to set different header color for nested paper-card?

### ISSUE THREAD

**Issue by edvail** [PolymerElements/paper-card#64]
Hi,

How to set different header color for nested paper-card?
It is always same as parent paper-card header color.

See example: http://jsbin.com/lohogu/edit?html,output

**Comment by bicknellr** [comment]
I think you might have stumbled on a more generic Polymer bug:

![screen shot 2016-02-02 at 15 03 44](https://cloud.githubusercontent.com/assets/406614/12767479/42cc23fe-c9be-11e5-872b-413d0d5b7395.png)

**Comment by edvail** [comment]
Can it be workarounded somehow?

**Comment by kriswillis** [comment]
I'd just stumbled across the same issue, adding `!important` works for me…

```
paper-card {
  width: 100%;

  --paper-card-header: {
    background-color: var(--paper-blue-900);
  };

  --paper-card-header-color: #fff !important;
}
```

**Comment by notwaldorf** [comment]
Closing, there seems to be a fix.
