### ISSUE TITLE
Cannot set placeholder image

### ISSUE THREAD

**Issue by socceroos** [PolymerElements/paper-card#66]
`
<paper-card preload placeholder="/images/placeholder.png" image="/images/[[id]].png" class="flex">
      <div class="card-content">
        <div class="header">[[name]]
        </div>
        <p class='light'>by [[author]]</p>
      </div>
    </paper-card>
`
Despite setting the preload and placeholder properties, if 'image' fails to load, there is still no placeholder shown.

**Comment by egut** [comment]
I don't know if you have got an answer on this but as I got into a similar issue I know the answer.
You have misswritten the arguments you need to use preload-image (and fade-image if you like) try this instead:

```html
<paper-card preload-image placeholder="/images/placeholder.png" image="/images/[[id]].png" class="flex"> 
   <div class="card-content"> 
       <div class="header">[[name]] </div> 
       <p class='light'>by [[author]]</p> 
   </div> 
</paper-card> 
```

**Comment by socceroos** [comment]
Thank you!! I'll give this a try this weekend.

**Comment by togonow** [comment]
I have the same issue too, i've tried different combinations (note i don't think preload-image is correct) and still nothing shows the place holder i even embeded it as a base 64 URI

```
<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>paper-card</title>

  <script src="../webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="./paper-card.html">
</head>
<body>
  <img src="./demo/cafe.png" />
  <paper-card heading="header"
    image="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97350&w=1350&h=1350"    fadeImage    preload-image    preloadImage    preload    placeholder="./demo/cafe.png"    placeholderImage="./demo/cafe.png">
    <div class="card-content"><p>Sample content</p></div>
  </paper-card>
</body>
</html>
```

**Comment by dman777** [comment]
It works for me(although it tiles). Make sure you prefex the base64 encoded string with `placeholder-image="data:image/jpeg;base64,here you place the base65 string`

**Comment by ankitsorathiya** [comment]
Does it work with the url in placeholder-image instead base64 input? 
I tried but it doesn't seem to work. Does anyone has solution for this?
