### ISSUE TITLE
Support Mini-cards

### ISSUE THREAD

**Issue by phidias51** [PolymerElements/paper-card#76]
The current paper-card uses a large amount of screen real-estate to display a card.  It would be useful if there was a mini-card version similar to what you see in Google Newsstand.

**Comment by notwaldorf** [comment]
This is already possible with the styling [mixins](https://github.com/PolymerElements/paper-card/blob/master/paper-card.html#L45) available.

For example this code:
```
<style is="custom-style">
    paper-card.news {
      width: 150px;
      --paper-card-header-image: {
        height: 120px;
      }
    }
</style>

<paper-card class="news" image="http://placehold.it/150x350/FFC107/000000" alt="Emmental">
    <div class="card-content">
      Hi!
    </div>
    <div class="card-actions">
        <iron-icon class="star" icon="star"></iron-icon>
        <iron-icon class="star" icon="star"></iron-icon>
        <iron-icon class="star" icon="star"></iron-icon>
        <iron-icon class="star" icon="star"></iron-icon>
        <iron-icon class="star" icon="star"></iron-icon>
      </div>
  </paper-card>
```

Produces this card:
<img width="446" alt="screen shot 2017-04-17 at 6 22 09" src="https://cloud.githubusercontent.com/assets/1369170/25110719/f74208d0-239a-11e7-802e-386fd421f8a8.png">

**Comment by phidias51** [comment]
That's more of a tile than a mini card. Mini cards usually have a thumbnail to the left or right of the text, a bold headline and a short text summary that uses a text-overflow: ellipsis style. Here's an example from Feedly, but a similar layout is used in Google News, and Google Play Newstand.

https://goo.gl/photos/v9quVx6ZBGiycXxp8

**Comment by notwaldorf** [comment]
Did you look at the demo? One of the samples is very similar:
<img width="419" alt="screen shot 2017-04-18 at 8 41 50" src="https://cloud.githubusercontent.com/assets/1369170/25139698/ea305ba6-2412-11e7-9dd3-4a9f94f2294e.png">

All of the styles are controlled by the user, so if you want to make the text smaller and have less padding, that's totally a thing you can do
