### ISSUE TITLE
Paper Card's heading is duplicated when dragged

### ISSUE THREAD

**Issue by andrew-vandenbrink** [PolymerElements/paper-card#80]
When using paper-card with kendo sortable
http://demos.telerik.com/kendo-ui/sortable/index

The header is somehow duplicated when I drag it

![image](https://cloud.githubusercontent.com/assets/12871379/18161634/03d70e90-7033-11e6-8aec-47c0515b148b.png)

![image](https://cloud.githubusercontent.com/assets/12871379/18161655/1ee05214-7033-11e6-82b4-ab8abe5d1d87.png)

```
<div class="content">
    <div class="vertical-section-container centered">
        <ul class="container">
            <li class="list-item">
                <paper-card heading="">
                    <div class="card-content">Some content</div><div class="card-actions">
                        <paper-button>Some action</paper-button>
                    </div>
                </paper-card>
            </li>
            <li class="list-item"> <paper-card heading="Me too!"><div class="card-content">Some content</div></paper-card></li>
        </ul>
    </div>
</div>

```

It's not happening if you keep heading empty or you use image on paper-card

**Comment by notwaldorf** [comment]
I'm not really sure what the library is doing, but please make sure you're calling `Polymer.dom(someElement).appendChild` if you're doing any dom manipulations.

Closing, as there's no repro steps that I can debug, but we can re-open this if you can post a JSBin with a small example reproducing your case
