### ISSUE TITLE
placeholder-image creates background-repeat

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-card#82]
### Description

`placeholder-image` creates background-repeat and tiles image
### Expected outcome

Single place holder image should cover area instead of repeat image in a tiled fashion. 
### Actual outcome

Tiny place holder image repeats 
### Steps to reproduce

``` html
 placeholder-image="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIF/8QAIRAAAQQBAwUAAAAAAAAAAAAAAQACAxEEBQYhEhMzcYH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBf/EABsRAAIBBQAAAAAAAAAAAAAAAAABADAMBAAIRAxEAPwCtOxsmbQ8pskUXbicBTwCHWbv2LJ+rKO2cN5LutvPPjCIot7PXEliPzo//2Q=="
```
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by bechirmedini** [comment]
Hi,

this works fine...

`  
  paper-card {
        --iron-image-placeholder : {
        	background-repeat: no-repeat;
	        background-size: cover;
        }
  
  }
`
bye.

**Comment by notwaldorf** [comment]
Closing, as there seems to be a fix
