### ISSUE TITLE
add style customisation over header image

### ISSUE THREAD

**Issue by bsorrentino** [PolymerElements/paper-card#9]
Hi all

I'm using paper-card element in my mobile app.

I needed to customise header image, is it possible adding a custom CSS property to allow this ?

Example
```css
 .header img {
    pointer-events: none;
    @apply(--paper-card-header-image);
```

**Comment by notwaldorf** [comment]
Yup, sounds fine. Making a PR right now :)

**Comment by bsorrentino** [comment]
Great ;)

I'll wait for it

Thanks
