### ISSUE TITLE
2.0-preview throw an error Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes

### ISSUE THREAD

**Issue by KitaitiMakoto** [PolymerElements/paper-card#90]
### Description

As using 2.0-preview branch, `paper-card` doesn't work on Chrome. It seems to due to adding class `paper-material` in *created* callback. If we do so in ready callback, any error is not thrown.

For `paper-button`, the same error appears.

### Expected outcome

It should not throw any error.

### Actual outcome

It outputs error message

> Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes

in console.

### Steps to reproduce

1. Use `paper-card` in any document.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
I just tested with the latest version of `polymer#2.0-preview`, and it looks fine. Can you run `bower cache clean && bower install` and try again?

**Comment by KitaitiMakoto** [comment]
Thank you for the reply.
I cleaned cache but the issue is still remaining.

I found this tiny HTML works fine in Chrome:

    $ bower install 'PaperElements/paper-card#2.0-preview'

```html
<!doctype html>
<title>Paper Card</title>
<script src=bower_components/webcomponentsjs/webcomponents-lite.js></script>
<link href=bower_components/paper-card/paper-card.html rel=import></script>

<paper-card heading="Card Title">
  <div class="card-content">Some content</div>
  <div class="card-actions">
    <paper-button>Some action</paper-button>
  </div>
</paper-card>
```

But, after I vulcanized, it doesn't work and error messages as I reported are output.

    $ vulcanize index.html > index.vulcanized.html

This seems an issue related to vulcanize rather than `paper-card`. So, I close this issue and will research vulcanize more.

Thank you.

**Comment by KitaitiMakoto** [comment]
FYI, I found a related issue: https://github.com/Polymer/vulcanize/issues/263
