### ISSUE TITLE
Question: Is there a way to control font-size of headline?

### ISSUE THREAD

**Issue by atifwaqar** [PolymerElements/paper-card#94]
My code looks like :
```
<paper-card heading="0 Live Campaigns">
	<div class="card-actions">
		<div>
			....
			{{model.CampaignsStats}}
			....
		</div>									  
	</div>
</paper-card>
```
but I want to increase/decrease the header font size depending on its content size, and also want to center allign the header. I tried to find some reference in your code examples, but couldn't find it.
Any sort of help would be really appreciated. 
Thanks in advance :)

**Comment by notwaldorf** [comment]
Yup, there's the `--paper-card-header-text` mixin:

```
paper-card.smaller-text {
      --paper-card-header-text: {
        font-size: 10px;
      };
}
```
