### ISSUE TITLE
paper-card is not found in bower

### ISSUE THREAD

**Issue by lawrencemok** [PolymerElements/paper-card#97]
paper-card is not found in bower, tried searching from https://bower.io/search/ , the one listed is not from PolymerElements

**Comment by abdonrd** [comment]
Polymer doesn't use the bower registry.
You should use `bower install PolymerElements/element-name`.
In this case: `bower install PolymerElements/paper-card`.

**Comment by notwaldorf** [comment]
Yup, @abdonrd is right! `bower install PolymerElements/paper-card` is the winner

**Comment by lawrencemok** [comment]
thanks!
